name: My Homepage Workflow  #workflow 이름
on:                         #해당 workflow가 언제 실행되는지 정의
  push:                     #push 이벤트 발생시 workflow 실행
    branches: ["main"]      #main branch에서 push 이벤트 발생시 workflow 실행

jobs:                       #workflow에서 진행할 하나 이상의 job들을 정의
  build:                    #build라는 식별자를 가진 job 정의
    runs-on: ubuntu-latest  #ubuntu-latest OS 환경에서 build job 수행 
    env:                    #build job에서 사용할 변수
      OWNER: 'taeyoung'    #build job에서 사용할 변수 OWNER 선언 및 정의
    steps:                      #앞으로 실행시킬 step들
      - uses: actions/checkout@v3 #깃허브에서 제공하는 checkout actionv3

      - name: Install dependencies # step이름 정의
        run: |              #shell을 이용하여 command line 실행  1.pip upgrade, 2. pytest install 
          pip install --upgrade pip       
          pip install ruff pytest
      - name: testing      #step 이름 정의
        run: |              #shell을 이용하여 command line 실행 (test.py를 테스트한다)
          pytest test.py